// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.1
//   protoc               v6.33.4
// source: src/proto/workdays.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import type { handleUnaryCall, UntypedServiceImplementation } from "@grpc/grpc-js";

export const protobufPackage = "plannify";

export interface Workday {
  date: string;
  startTime: string;
  endTime?: string | undefined;
  restTime: string;
  overnight: boolean;
}

export interface GenerateMonthlyWorkdayReportRequest {
  driverFirstname: string;
  driverLastname: string;
  month: number;
  year: number;
  workdays: Workday[];
}

export interface GenerateMonthlyWorkdayReportResponse {
  pdfContent: Uint8Array;
}

function createBaseWorkday(): Workday {
  return { date: "", startTime: "", endTime: undefined, restTime: "", overnight: false };
}

export const Workday: MessageFns<Workday> = {
  encode(message: Workday, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.date !== "") {
      writer.uint32(10).string(message.date);
    }
    if (message.startTime !== "") {
      writer.uint32(18).string(message.startTime);
    }
    if (message.endTime !== undefined) {
      writer.uint32(26).string(message.endTime);
    }
    if (message.restTime !== "") {
      writer.uint32(34).string(message.restTime);
    }
    if (message.overnight !== false) {
      writer.uint32(40).bool(message.overnight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Workday {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkday();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.date = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.startTime = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.endTime = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.restTime = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.overnight = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Workday {
    return {
      date: isSet(object.date) ? globalThis.String(object.date) : "",
      startTime: isSet(object.startTime)
        ? globalThis.String(object.startTime)
        : isSet(object.start_time)
        ? globalThis.String(object.start_time)
        : "",
      endTime: isSet(object.endTime)
        ? globalThis.String(object.endTime)
        : isSet(object.end_time)
        ? globalThis.String(object.end_time)
        : undefined,
      restTime: isSet(object.restTime)
        ? globalThis.String(object.restTime)
        : isSet(object.rest_time)
        ? globalThis.String(object.rest_time)
        : "",
      overnight: isSet(object.overnight) ? globalThis.Boolean(object.overnight) : false,
    };
  },

  toJSON(message: Workday): unknown {
    const obj: any = {};
    if (message.date !== "") {
      obj.date = message.date;
    }
    if (message.startTime !== "") {
      obj.startTime = message.startTime;
    }
    if (message.endTime !== undefined) {
      obj.endTime = message.endTime;
    }
    if (message.restTime !== "") {
      obj.restTime = message.restTime;
    }
    if (message.overnight !== false) {
      obj.overnight = message.overnight;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Workday>, I>>(base?: I): Workday {
    return Workday.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Workday>, I>>(object: I): Workday {
    const message = createBaseWorkday();
    message.date = object.date ?? "";
    message.startTime = object.startTime ?? "";
    message.endTime = object.endTime ?? undefined;
    message.restTime = object.restTime ?? "";
    message.overnight = object.overnight ?? false;
    return message;
  },
};

function createBaseGenerateMonthlyWorkdayReportRequest(): GenerateMonthlyWorkdayReportRequest {
  return { driverFirstname: "", driverLastname: "", month: 0, year: 0, workdays: [] };
}

export const GenerateMonthlyWorkdayReportRequest: MessageFns<GenerateMonthlyWorkdayReportRequest> = {
  encode(message: GenerateMonthlyWorkdayReportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.driverFirstname !== "") {
      writer.uint32(10).string(message.driverFirstname);
    }
    if (message.driverLastname !== "") {
      writer.uint32(18).string(message.driverLastname);
    }
    if (message.month !== 0) {
      writer.uint32(24).uint32(message.month);
    }
    if (message.year !== 0) {
      writer.uint32(32).uint32(message.year);
    }
    for (const v of message.workdays) {
      Workday.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateMonthlyWorkdayReportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateMonthlyWorkdayReportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.driverFirstname = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.driverLastname = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.month = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.year = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.workdays.push(Workday.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateMonthlyWorkdayReportRequest {
    return {
      driverFirstname: isSet(object.driverFirstname)
        ? globalThis.String(object.driverFirstname)
        : isSet(object.driver_firstname)
        ? globalThis.String(object.driver_firstname)
        : "",
      driverLastname: isSet(object.driverLastname)
        ? globalThis.String(object.driverLastname)
        : isSet(object.driver_lastname)
        ? globalThis.String(object.driver_lastname)
        : "",
      month: isSet(object.month) ? globalThis.Number(object.month) : 0,
      year: isSet(object.year) ? globalThis.Number(object.year) : 0,
      workdays: globalThis.Array.isArray(object?.workdays) ? object.workdays.map((e: any) => Workday.fromJSON(e)) : [],
    };
  },

  toJSON(message: GenerateMonthlyWorkdayReportRequest): unknown {
    const obj: any = {};
    if (message.driverFirstname !== "") {
      obj.driverFirstname = message.driverFirstname;
    }
    if (message.driverLastname !== "") {
      obj.driverLastname = message.driverLastname;
    }
    if (message.month !== 0) {
      obj.month = Math.round(message.month);
    }
    if (message.year !== 0) {
      obj.year = Math.round(message.year);
    }
    if (message.workdays?.length) {
      obj.workdays = message.workdays.map((e) => Workday.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateMonthlyWorkdayReportRequest>, I>>(
    base?: I,
  ): GenerateMonthlyWorkdayReportRequest {
    return GenerateMonthlyWorkdayReportRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateMonthlyWorkdayReportRequest>, I>>(
    object: I,
  ): GenerateMonthlyWorkdayReportRequest {
    const message = createBaseGenerateMonthlyWorkdayReportRequest();
    message.driverFirstname = object.driverFirstname ?? "";
    message.driverLastname = object.driverLastname ?? "";
    message.month = object.month ?? 0;
    message.year = object.year ?? 0;
    message.workdays = object.workdays?.map((e) => Workday.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGenerateMonthlyWorkdayReportResponse(): GenerateMonthlyWorkdayReportResponse {
  return { pdfContent: new Uint8Array(0) };
}

export const GenerateMonthlyWorkdayReportResponse: MessageFns<GenerateMonthlyWorkdayReportResponse> = {
  encode(message: GenerateMonthlyWorkdayReportResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pdfContent.length !== 0) {
      writer.uint32(10).bytes(message.pdfContent);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GenerateMonthlyWorkdayReportResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGenerateMonthlyWorkdayReportResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pdfContent = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GenerateMonthlyWorkdayReportResponse {
    return {
      pdfContent: isSet(object.pdfContent)
        ? bytesFromBase64(object.pdfContent)
        : isSet(object.pdf_content)
        ? bytesFromBase64(object.pdf_content)
        : new Uint8Array(0),
    };
  },

  toJSON(message: GenerateMonthlyWorkdayReportResponse): unknown {
    const obj: any = {};
    if (message.pdfContent.length !== 0) {
      obj.pdfContent = base64FromBytes(message.pdfContent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GenerateMonthlyWorkdayReportResponse>, I>>(
    base?: I,
  ): GenerateMonthlyWorkdayReportResponse {
    return GenerateMonthlyWorkdayReportResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GenerateMonthlyWorkdayReportResponse>, I>>(
    object: I,
  ): GenerateMonthlyWorkdayReportResponse {
    const message = createBaseGenerateMonthlyWorkdayReportResponse();
    message.pdfContent = object.pdfContent ?? new Uint8Array(0);
    return message;
  },
};

export type WorkdayServiceService = typeof WorkdayServiceService;
export const WorkdayServiceService = {
  generateMonthlyWorkdayReport: {
    path: "/plannify.WorkdayService/GenerateMonthlyWorkdayReport",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GenerateMonthlyWorkdayReportRequest): Buffer =>
      Buffer.from(GenerateMonthlyWorkdayReportRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GenerateMonthlyWorkdayReportRequest =>
      GenerateMonthlyWorkdayReportRequest.decode(value),
    responseSerialize: (value: GenerateMonthlyWorkdayReportResponse): Buffer =>
      Buffer.from(GenerateMonthlyWorkdayReportResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GenerateMonthlyWorkdayReportResponse =>
      GenerateMonthlyWorkdayReportResponse.decode(value),
  },
} as const;

export interface WorkdayServiceServer extends UntypedServiceImplementation {
  generateMonthlyWorkdayReport: handleUnaryCall<
    GenerateMonthlyWorkdayReportRequest,
    GenerateMonthlyWorkdayReportResponse
  >;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
